-- ===========================================================================
-- AGS Dismissal — complete schema, in one file
-- ---------------------------------------------------------------------------
-- GENERATED by scripts/build-install-sql.mjs. Do not edit: change the files in
-- supabase/migrations/ and run the script again.
--
-- Paste the whole file into the Supabase SQL editor and run it. It is the same
-- as `supabase db push`, for when there is no computer to run the CLI on. There
-- is nothing to fill in here.
--
-- Then run supabase/setup.sql, which creates the school, the classes and the
-- staff logins — that one has four values to edit at the top.
--
-- Run it ONCE. Migrations build on each other — the later ones change what the
-- earlier ones made — so replaying them is not the same as running them once.
-- The guard below stops a second run before it touches anything: if you see
-- "already installed", nothing was changed and you can go straight to
-- setup.sql.
--
-- Contains, in order:
--   20260101000000_schema.sql
--   20260101000001_security.sql
--   20260101000002_workflow.sql
--   20260101000003_classes.sql
--   20260101000004_roles.sql
--   20260101000005_scopes_and_promotion.sql
-- ===========================================================================

-- ###########################################################################
-- Guard: is this a fresh project, a finished one, or an interrupted paste?
--
-- This file is ~70 KB. A phone or a flaky editor can cut a paste short, and
-- what that used to leave behind was unrecoverable: too far in to install
-- cleanly, not far enough to be usable. So:
--
--   • finished already  -> stop, change nothing
--   • cut short         -> clear the remains and install properly
--   • cut short, but a school exists -> stop; that is real data, not debris
--
-- The SQL editor runs the whole paste as one transaction, so stopping here
-- leaves the database exactly as it was.
-- ###########################################################################

do $install_guard$
declare
  v_schools bigint := 0;
begin
  -- promote_all_students() is the last thing this file creates, so its
  -- presence is what proves the whole paste arrived.
  if exists (
    select 1
      from pg_proc p
      join pg_namespace n on n.oid = p.pronamespace
     where n.nspname = 'public' and p.proname = 'promote_all_students'
  ) then
    raise exception
      'AGS Dismissal is already installed. Nothing was changed — carry on with supabase/setup.sql.'
      using errcode = '42P07';
  end if;

  if to_regclass('public.schools') is not null then
    execute 'select count(*) from public.schools' into v_schools;
    if v_schools > 0 then
      raise exception
        'AGS Dismissal is only half installed but already holds a school. Nothing was changed — do not re-run this file; ask before going further.'
        using errcode = '42P07';
    end if;
  end if;

  -- Debris from a cut-short paste. Nothing can have been stored in it.
  drop view if exists public.dismissal_queue cascade;
  drop table if exists
    public.dismissal_events,
    public.dismissal_requests,
    public.guardians,
    public.students,
    public.classrooms,
    public.profiles,
    public.schools
    cascade;
  drop type if exists
    public.user_role,
    public.user_role_legacy,
    public.dismissal_status,
    public.request_source,
    public.class_gender,
    public.section_scope
    cascade;
end
$install_guard$;

-- ###########################################################################
-- 20260101000000_schema.sql
-- ###########################################################################

-- ===========================================================================
-- AGS Dismissal — core schema
-- ---------------------------------------------------------------------------
-- Multi-tenant by `school_id`. Every table that holds school data carries the
-- school id so Row Level Security can be expressed as a single, cheap check.
-- ===========================================================================

create extension if not exists "pgcrypto" with schema extensions;

-- ---------------------------------------------------------------------------
-- Enums
-- ---------------------------------------------------------------------------

create type public.user_role as enum ('admin', 'staff', 'parent', 'display');

-- The dismissal lifecycle. `requested` is created by a parent tapping
-- "I'm Here"; `waiting` is the same student acknowledged into the queue (staff
-- may also add students straight to `waiting`).
create type public.dismissal_status as enum (
  'requested',
  'waiting',
  'called',
  'ready',
  'picked_up',
  'cancelled'
);

create type public.request_source as enum ('parent_app', 'staff', 'kiosk');

-- ---------------------------------------------------------------------------
-- Schools
-- ---------------------------------------------------------------------------

create table public.schools (
  id                  uuid primary key default gen_random_uuid(),
  name                text not null check (length(trim(name)) > 0),
  slug                text not null unique check (slug ~ '^[a-z0-9-]{2,60}$'),
  logo_url            text,
  timezone            text not null default 'UTC',
  dismissal_start     time,
  dismissal_end       time,
  -- Feature switches a school administrator can flip in Settings.
  show_queue_position boolean not null default true,
  show_pickup_number  boolean not null default true,
  allow_parent_cancel boolean not null default true,
  board_message       text,
  board_accent        text not null default 'indigo',
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Profiles (1:1 with auth.users)
-- ---------------------------------------------------------------------------

create table public.profiles (
  id                  uuid primary key references auth.users (id) on delete cascade,
  school_id           uuid references public.schools (id) on delete set null,
  role                public.user_role not null default 'parent',
  full_name           text not null default '',
  email               text,
  phone               text,
  vehicle_description text,
  avatar_url          text,
  is_active           boolean not null default true,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index profiles_school_role_idx on public.profiles (school_id, role);

-- ---------------------------------------------------------------------------
-- Classrooms
-- ---------------------------------------------------------------------------

create table public.classrooms (
  id          uuid primary key default gen_random_uuid(),
  school_id   uuid not null references public.schools (id) on delete cascade,
  name        text not null check (length(trim(name)) > 0),
  grade       text not null default '',
  room_number text,
  teacher_id  uuid references public.profiles (id) on delete set null,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now(),
  unique (school_id, name)
);

create index classrooms_school_idx on public.classrooms (school_id);

-- ---------------------------------------------------------------------------
-- Students
-- ---------------------------------------------------------------------------

create table public.students (
  id            uuid primary key default gen_random_uuid(),
  school_id     uuid not null references public.schools (id) on delete cascade,
  first_name    text not null check (length(trim(first_name)) > 0),
  last_name     text not null default '',
  grade         text not null default '',
  classroom_id  uuid references public.classrooms (id) on delete set null,
  pickup_number text,
  photo_url     text,
  notes         text,
  is_active     boolean not null default true,
  created_at    timestamptz not null default now(),
  updated_at    timestamptz not null default now()
);

create index students_school_idx on public.students (school_id);
create index students_classroom_idx on public.students (classroom_id);
-- Deliberately not unique: siblings normally share one family pickup number.
create index students_pickup_number_idx
  on public.students (school_id, pickup_number)
  where pickup_number is not null and pickup_number <> '';

-- ---------------------------------------------------------------------------
-- Guardians — the pickup-permission table.
-- A parent/driver may only ever see (and request) students they are linked to.
-- ---------------------------------------------------------------------------

create table public.guardians (
  id           uuid primary key default gen_random_uuid(),
  student_id   uuid not null references public.students (id) on delete cascade,
  profile_id   uuid not null references public.profiles (id) on delete cascade,
  relationship text not null default 'Guardian',
  is_primary   boolean not null default false,
  can_pickup   boolean not null default true,
  created_at   timestamptz not null default now(),
  unique (student_id, profile_id)
);

create index guardians_profile_idx on public.guardians (profile_id);
create index guardians_student_idx on public.guardians (student_id);

-- ---------------------------------------------------------------------------
-- Dismissal requests — the live queue.
--
-- Student details are snapshotted onto the row on insert. The display board is
-- then a single-table read (no joins, no extra RLS surface) and history stays
-- accurate even if a student is later renamed or moves classroom.
-- ---------------------------------------------------------------------------

create table public.dismissal_requests (
  id                  uuid primary key default gen_random_uuid(),
  school_id           uuid not null references public.schools (id) on delete cascade,
  student_id          uuid not null references public.students (id) on delete cascade,
  status              public.dismissal_status not null default 'requested',
  source              public.request_source not null default 'staff',

  requested_by        uuid references public.profiles (id) on delete set null,
  called_by           uuid references public.profiles (id) on delete set null,
  released_by         uuid references public.profiles (id) on delete set null,

  requested_at        timestamptz not null default now(),
  called_at           timestamptz,
  ready_at            timestamptz,
  picked_up_at        timestamptz,
  cancelled_at        timestamptz,

  cancel_reason       text,
  vehicle_description text,
  note                text,
  dismissal_date      date not null default current_date,

  -- Denormalised snapshots (maintained by trigger).
  student_name        text not null default '',
  student_grade       text,
  classroom_name      text,
  pickup_number       text,
  guardian_name       text,

  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now()
);

create index dismissal_requests_board_idx
  on public.dismissal_requests (school_id, dismissal_date, status);
create index dismissal_requests_student_idx
  on public.dismissal_requests (student_id, requested_at desc);
create index dismissal_requests_requester_idx
  on public.dismissal_requests (requested_by, requested_at desc);
create index dismissal_requests_called_idx
  on public.dismissal_requests (school_id, called_at desc);

-- A student can only be in the live queue once at a time.
create unique index dismissal_requests_one_active_per_student_idx
  on public.dismissal_requests (student_id)
  where status in ('requested', 'waiting', 'called', 'ready');

-- ---------------------------------------------------------------------------
-- Audit trail — every status transition, who made it and when.
-- ---------------------------------------------------------------------------

create table public.dismissal_events (
  id          bigint generated always as identity primary key,
  request_id  uuid not null references public.dismissal_requests (id) on delete cascade,
  school_id   uuid not null references public.schools (id) on delete cascade,
  actor_id    uuid references public.profiles (id) on delete set null,
  actor_name  text,
  from_status public.dismissal_status,
  to_status   public.dismissal_status not null,
  created_at  timestamptz not null default now()
);

create index dismissal_events_request_idx on public.dismissal_events (request_id, created_at);
create index dismissal_events_school_idx on public.dismissal_events (school_id, created_at desc);

-- ###########################################################################
-- 20260101000001_security.sql
-- ###########################################################################

-- ===========================================================================
-- AGS Dismissal — authorization helpers + Row Level Security
-- ---------------------------------------------------------------------------
-- Every policy is expressed in terms of the four helpers below. They are
-- SECURITY DEFINER so that reading the caller's own profile does not re-enter
-- the policies on `profiles` (which would recurse).
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Timestamps
-- ---------------------------------------------------------------------------

create or replace function public.tg_touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

create trigger touch_schools before update on public.schools
  for each row execute function public.tg_touch_updated_at();
create trigger touch_profiles before update on public.profiles
  for each row execute function public.tg_touch_updated_at();
create trigger touch_classrooms before update on public.classrooms
  for each row execute function public.tg_touch_updated_at();
create trigger touch_students before update on public.students
  for each row execute function public.tg_touch_updated_at();
create trigger touch_dismissal_requests before update on public.dismissal_requests
  for each row execute function public.tg_touch_updated_at();

-- ---------------------------------------------------------------------------
-- Auth helpers
-- ---------------------------------------------------------------------------

create or replace function public.current_school_id()
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select school_id from public.profiles where id = auth.uid() and is_active;
$$;

create or replace function public.current_role_name()
returns public.user_role
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select role from public.profiles where id = auth.uid() and is_active;
$$;

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_active and role in ('admin', 'staff')
  );
$$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_active and role = 'admin'
  );
$$;

-- Board displays get read-only access to the queue, nothing else.
create or replace function public.is_board_viewer()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_active and role in ('admin', 'staff', 'display')
  );
$$;

-- True when the caller is an authorised guardian of the student.
create or replace function public.is_guardian_of(p_student_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.guardians g
    join public.profiles p on p.id = g.profile_id
    where g.student_id = p_student_id
      and g.profile_id = auth.uid()
      and g.can_pickup
      and p.is_active
  );
$$;

-- True when the caller is linked to the student at all (even if pickup is
-- currently blocked) — this is what "may see this student" means.
create or replace function public.is_linked_guardian(p_student_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.guardians
    where student_id = p_student_id and profile_id = auth.uid()
  );
$$;

-- The helpers below exist so that a policy on one table never has to SELECT
-- another RLS-protected table. Without them `students` -> `guardians` ->
-- `students` recurses and Postgres aborts the query.
create or replace function public.student_school_id(p_student_id uuid)
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select school_id from public.students where id = p_student_id;
$$;

create or replace function public.request_student_id(p_request_id uuid)
returns uuid
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select student_id from public.dismissal_requests where id = p_request_id;
$$;

create or replace function public.is_guardian_classroom(p_classroom_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1
    from public.students s
    join public.guardians g on g.student_id = s.id
    where s.classroom_id = p_classroom_id and g.profile_id = auth.uid()
  );
$$;

grant execute on function public.current_school_id() to authenticated;
grant execute on function public.current_role_name() to authenticated;
grant execute on function public.is_staff() to authenticated;
grant execute on function public.is_admin() to authenticated;
grant execute on function public.is_board_viewer() to authenticated;
grant execute on function public.is_guardian_of(uuid) to authenticated;
grant execute on function public.is_linked_guardian(uuid) to authenticated;
grant execute on function public.student_school_id(uuid) to authenticated;
grant execute on function public.request_student_id(uuid) to authenticated;
grant execute on function public.is_guardian_classroom(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- New auth user -> profile
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, school_id, role, full_name, email, phone)
  values (
    new.id,
    nullif(new.raw_user_meta_data ->> 'school_id', '')::uuid,
    coalesce(nullif(new.raw_user_meta_data ->> 'role', ''), 'parent')::public.user_role,
    coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), split_part(new.email, '@', 1)),
    new.email,
    nullif(new.raw_user_meta_data ->> 'phone', '')
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = case
          when public.profiles.full_name = '' then excluded.full_name
          else public.profiles.full_name
        end;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ---------------------------------------------------------------------------
-- Snapshot student + guardian details onto a request
-- ---------------------------------------------------------------------------

create or replace function public.tg_snapshot_request()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_student record;
  v_tz      text;
begin
  select s.school_id,
         trim(s.first_name || ' ' || s.last_name) as full_name,
         s.grade,
         s.pickup_number,
         c.name as classroom_name
    into v_student
    from public.students s
    left join public.classrooms c on c.id = s.classroom_id
   where s.id = new.student_id;

  if v_student is null then
    raise exception 'Student % does not exist', new.student_id
      using errcode = 'foreign_key_violation';
  end if;

  new.school_id      := v_student.school_id;
  new.student_name   := v_student.full_name;
  new.student_grade  := v_student.grade;
  new.classroom_name := v_student.classroom_name;
  new.pickup_number  := coalesce(nullif(new.pickup_number, ''), v_student.pickup_number);

  select timezone into v_tz from public.schools where id = new.school_id;
  new.dismissal_date := (now() at time zone coalesce(v_tz, 'UTC'))::date;

  if new.requested_by is not null then
    select full_name into new.guardian_name from public.profiles where id = new.requested_by;
  end if;

  return new;
end;
$$;

create trigger snapshot_dismissal_request
  before insert on public.dismissal_requests
  for each row execute function public.tg_snapshot_request();

-- ---------------------------------------------------------------------------
-- Audit trail
-- ---------------------------------------------------------------------------

create or replace function public.tg_log_dismissal_event()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_actor_name text;
begin
  if tg_op = 'UPDATE' and new.status is not distinct from old.status then
    return new;
  end if;

  select full_name into v_actor_name from public.profiles where id = auth.uid();

  insert into public.dismissal_events (request_id, school_id, actor_id, actor_name, from_status, to_status)
  values (
    new.id,
    new.school_id,
    auth.uid(),
    v_actor_name,
    case when tg_op = 'UPDATE' then old.status end,
    new.status
  );

  return new;
end;
$$;

create trigger log_dismissal_request_event
  after insert or update on public.dismissal_requests
  for each row execute function public.tg_log_dismissal_event();

-- ===========================================================================
-- Row Level Security
-- ===========================================================================

alter table public.schools            enable row level security;
alter table public.profiles           enable row level security;
alter table public.classrooms         enable row level security;
alter table public.students           enable row level security;
alter table public.guardians          enable row level security;
alter table public.dismissal_requests enable row level security;
alter table public.dismissal_events   enable row level security;

-- --- schools ---------------------------------------------------------------

create policy "school members read their school"
  on public.schools for select to authenticated
  using (id = public.current_school_id());

create policy "admins update their school"
  on public.schools for update to authenticated
  using (id = public.current_school_id() and public.is_admin())
  with check (id = public.current_school_id() and public.is_admin());

-- --- profiles --------------------------------------------------------------

create policy "read own profile"
  on public.profiles for select to authenticated
  using (id = auth.uid());

create policy "staff read profiles in their school"
  on public.profiles for select to authenticated
  using (school_id = public.current_school_id() and public.is_staff());

create policy "update own profile"
  on public.profiles for update to authenticated
  using (id = auth.uid())
  with check (id = auth.uid());

create policy "admins manage profiles in their school"
  on public.profiles for update to authenticated
  using (school_id = public.current_school_id() and public.is_admin())
  with check (school_id = public.current_school_id() and public.is_admin());

create policy "admins delete profiles in their school"
  on public.profiles for delete to authenticated
  using (school_id = public.current_school_id() and public.is_admin() and id <> auth.uid());

-- --- classrooms ------------------------------------------------------------

create policy "staff read classrooms"
  on public.classrooms for select to authenticated
  using (school_id = public.current_school_id() and public.is_board_viewer());

create policy "guardians read classrooms of their students"
  on public.classrooms for select to authenticated
  using (public.is_guardian_classroom(classrooms.id));

create policy "admins manage classrooms"
  on public.classrooms for all to authenticated
  using (school_id = public.current_school_id() and public.is_admin())
  with check (school_id = public.current_school_id() and public.is_admin());

-- --- students --------------------------------------------------------------
-- Parents can only ever read students they are an authorised guardian for.

create policy "staff read students in their school"
  on public.students for select to authenticated
  using (school_id = public.current_school_id() and public.is_staff());

create policy "guardians read their own students"
  on public.students for select to authenticated
  using (public.is_linked_guardian(students.id));

create policy "admins manage students"
  on public.students for all to authenticated
  using (school_id = public.current_school_id() and public.is_admin())
  with check (school_id = public.current_school_id() and public.is_admin());

-- --- guardians -------------------------------------------------------------

create policy "read own guardian links"
  on public.guardians for select to authenticated
  using (profile_id = auth.uid());

create policy "staff read guardian links in their school"
  on public.guardians for select to authenticated
  using (
    public.is_staff()
    and public.student_school_id(guardians.student_id) = public.current_school_id()
  );

create policy "admins manage guardian links"
  on public.guardians for all to authenticated
  using (
    public.is_admin()
    and public.student_school_id(guardians.student_id) = public.current_school_id()
  )
  with check (
    public.is_admin()
    and public.student_school_id(guardians.student_id) = public.current_school_id()
  );

-- --- dismissal_requests ----------------------------------------------------
-- Reads are open to the right people so that Realtime can stream changes
-- straight to the browser. Writes go exclusively through the SECURITY DEFINER
-- functions in the next migration, which enforce the state machine.

create policy "staff and boards read the queue"
  on public.dismissal_requests for select to authenticated
  using (school_id = public.current_school_id() and public.is_board_viewer());

create policy "guardians read requests for their students"
  on public.dismissal_requests for select to authenticated
  using (public.is_linked_guardian(dismissal_requests.student_id));

-- --- dismissal_events ------------------------------------------------------

create policy "staff read the audit trail"
  on public.dismissal_events for select to authenticated
  using (school_id = public.current_school_id() and public.is_staff());

create policy "guardians read events for their students"
  on public.dismissal_events for select to authenticated
  using (public.is_linked_guardian(public.request_student_id(dismissal_events.request_id)));

-- ###########################################################################
-- 20260101000002_workflow.sql
-- ###########################################################################

-- ===========================================================================
-- AGS Dismissal — dismissal workflow
-- ---------------------------------------------------------------------------
-- The queue is only ever mutated through the functions below. They own the
-- state machine (who may move a request where, and which timestamps that
-- writes) so the same rules apply to every client: web, mobile, or a future
-- kiosk. `dismissal_requests` itself has no INSERT/UPDATE/DELETE policy, so a
-- compromised browser token cannot bypass them.
-- ===========================================================================

-- ---------------------------------------------------------------------------
-- Queue view — adds the live position a parent sees ("3rd in line").
-- security_invoker keeps the caller's RLS on the underlying table.
-- ---------------------------------------------------------------------------

create or replace view public.dismissal_queue
with (security_invoker = on) as
select
  r.*,
  case
    when r.status in ('requested', 'waiting') then (
      select count(*) + 1
      from public.dismissal_requests peer
      where peer.school_id = r.school_id
        and peer.dismissal_date = r.dismissal_date
        and peer.status in ('requested', 'waiting')
        and peer.requested_at < r.requested_at
    )
  end as queue_position,
  (
    select count(*)
    from public.dismissal_requests peer
    where peer.school_id = r.school_id
      and peer.dismissal_date = r.dismissal_date
      and peer.status in ('requested', 'waiting')
  ) as queue_length
from public.dismissal_requests r;

grant select on public.dismissal_queue to authenticated;

-- ---------------------------------------------------------------------------
-- Internal guards
-- ---------------------------------------------------------------------------

create or replace function public.require_profile()
returns public.profiles
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile public.profiles;
begin
  if auth.uid() is null then
    raise exception 'You must be signed in.' using errcode = '28000';
  end if;

  select * into v_profile from public.profiles where id = auth.uid();

  if v_profile is null or not v_profile.is_active then
    raise exception 'Your account is not active. Contact a school administrator.'
      using errcode = '28000';
  end if;

  return v_profile;
end;
$$;

create or replace function public.require_staff()
returns public.profiles
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile public.profiles := public.require_profile();
begin
  if v_profile.role not in ('admin', 'staff') then
    raise exception 'Only school staff can manage the dismissal queue.'
      using errcode = '42501';
  end if;
  return v_profile;
end;
$$;

-- ---------------------------------------------------------------------------
-- Parent / driver: "I'm here"
-- ---------------------------------------------------------------------------

create or replace function public.request_dismissal(
  p_student_ids uuid[],
  p_note text default null,
  p_vehicle text default null
)
returns setof public.dismissal_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile  public.profiles := public.require_profile();
  v_student  uuid;
  v_existing public.dismissal_requests;
  v_new      public.dismissal_requests;
begin
  if p_student_ids is null or array_length(p_student_ids, 1) is null then
    raise exception 'Choose at least one student.' using errcode = '22023';
  end if;

  foreach v_student in array p_student_ids loop
    if not public.is_guardian_of(v_student) then
      raise exception 'You are not authorised to pick up this student.'
        using errcode = '42501';
    end if;

    -- Tapping "I'm Here" twice must not create a duplicate or fail loudly.
    select * into v_existing
      from public.dismissal_requests
     where student_id = v_student
       and status in ('requested', 'waiting', 'called', 'ready')
     limit 1;

    if v_existing.id is not null then
      return next v_existing;
      continue;
    end if;

    insert into public.dismissal_requests (
      student_id, status, source, requested_by, note, vehicle_description
    )
    values (
      v_student,
      'requested',
      'parent_app',
      v_profile.id,
      nullif(trim(coalesce(p_note, '')), ''),
      coalesce(nullif(trim(coalesce(p_vehicle, '')), ''), v_profile.vehicle_description)
    )
    returning * into v_new;

    return next v_new;
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff: add a student to the queue directly
-- ---------------------------------------------------------------------------

create or replace function public.staff_add_to_queue(
  p_student_id uuid,
  p_note text default null
)
returns public.dismissal_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile  public.profiles := public.require_staff();
  v_school   uuid;
  v_existing public.dismissal_requests;
  v_new      public.dismissal_requests;
begin
  select school_id into v_school from public.students where id = p_student_id and is_active;

  if v_school is null or v_school <> v_profile.school_id then
    raise exception 'That student is not enrolled at your school.' using errcode = '42501';
  end if;

  select * into v_existing
    from public.dismissal_requests
   where student_id = p_student_id
     and status in ('requested', 'waiting', 'called', 'ready')
   limit 1;

  if v_existing.id is not null then
    return v_existing;
  end if;

  insert into public.dismissal_requests (student_id, status, source, requested_by, note)
  values (p_student_id, 'waiting', 'staff', v_profile.id, nullif(trim(coalesce(p_note, '')), ''))
  returning * into v_new;

  return v_new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff: move a request through the lifecycle (also used for undo)
-- ---------------------------------------------------------------------------

create or replace function public.set_request_status(
  p_request_id uuid,
  p_status public.dismissal_status
)
returns public.dismissal_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile public.profiles := public.require_staff();
  v_request public.dismissal_requests;
  v_now     timestamptz := now();
begin
  select * into v_request from public.dismissal_requests where id = p_request_id;

  if v_request.id is null or v_request.school_id <> v_profile.school_id then
    raise exception 'That dismissal request could not be found.' using errcode = 'P0002';
  end if;

  if p_status = 'cancelled' then
    raise exception 'Use cancel_request() to cancel a dismissal.' using errcode = '22023';
  end if;

  if p_status = 'requested' then
    raise exception 'Only a parent or driver can create an arrival request.'
      using errcode = '22023';
  end if;

  update public.dismissal_requests
     set status       = p_status,
         -- Moving backwards clears the timestamps that no longer apply, so the
         -- board and the parent app never show a stale "Called at ...".
         called_at    = case
                          when p_status = 'waiting' then null
                          when p_status = 'called'  then v_now
                          else coalesce(called_at, v_now)
                        end,
         called_by    = case
                          when p_status = 'waiting' then null
                          when p_status = 'called'  then v_profile.id
                          else coalesce(called_by, v_profile.id)
                        end,
         ready_at     = case
                          when p_status in ('waiting', 'called') then null
                          when p_status = 'ready' then v_now
                          else coalesce(ready_at, v_now)
                        end,
         picked_up_at = case when p_status = 'picked_up' then v_now else null end,
         released_by  = case when p_status = 'picked_up' then v_profile.id else null end,
         cancelled_at = null,
         cancel_reason = null
   where id = p_request_id
   returning * into v_request;

  return v_request;
exception
  when unique_violation then
    raise exception 'That student already has another active dismissal in the queue.'
      using errcode = '23505';
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff: call the next student in line
-- ---------------------------------------------------------------------------

create or replace function public.call_next_student()
returns public.dismissal_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile public.profiles := public.require_staff();
  v_next    uuid;
begin
  select id into v_next
    from public.dismissal_requests
   where school_id = v_profile.school_id
     and status in ('requested', 'waiting')
   order by requested_at asc
   limit 1
   for update skip locked;

  if v_next is null then
    return null;
  end if;

  return public.set_request_status(v_next, 'called');
end;
$$;

-- ---------------------------------------------------------------------------
-- Cancel — staff always, guardians only while still waiting
-- ---------------------------------------------------------------------------

create or replace function public.cancel_request(
  p_request_id uuid,
  p_reason text default null
)
returns public.dismissal_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile       public.profiles := public.require_profile();
  v_request       public.dismissal_requests;
  v_parent_cancel boolean;
begin
  select * into v_request from public.dismissal_requests where id = p_request_id;

  if v_request.id is null then
    raise exception 'That dismissal request could not be found.' using errcode = 'P0002';
  end if;

  if v_request.status in ('picked_up', 'cancelled') then
    raise exception 'That dismissal is already closed.' using errcode = '22023';
  end if;

  if v_profile.role in ('admin', 'staff') then
    if v_request.school_id <> v_profile.school_id then
      raise exception 'That dismissal request belongs to another school.' using errcode = '42501';
    end if;
  else
    if not public.is_guardian_of(v_request.student_id) then
      raise exception 'You are not authorised to change this dismissal.' using errcode = '42501';
    end if;

    select allow_parent_cancel into v_parent_cancel
      from public.schools where id = v_request.school_id;

    if not coalesce(v_parent_cancel, false) then
      raise exception 'Your school asks that you contact the office to cancel a pickup.'
        using errcode = '42501';
    end if;

    if v_request.status not in ('requested', 'waiting') then
      raise exception 'Your student has already been called — please speak to a staff member.'
        using errcode = '22023';
    end if;
  end if;

  update public.dismissal_requests
     set status        = 'cancelled',
         cancelled_at  = now(),
         cancel_reason = nullif(trim(coalesce(p_reason, '')), '')
   where id = p_request_id
   returning * into v_request;

  return v_request;
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff: close out the day
-- ---------------------------------------------------------------------------

create or replace function public.end_dismissal_session()
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile public.profiles := public.require_staff();
  v_count   integer;
begin
  update public.dismissal_requests
     set status        = 'cancelled',
         cancelled_at  = now(),
         cancel_reason = 'Dismissal session ended'
   where school_id = v_profile.school_id
     and status in ('requested', 'waiting', 'called', 'ready');

  get diagnostics v_count = row_count;
  return v_count;
end;
$$;

-- ---------------------------------------------------------------------------
-- Grants — these are SECURITY DEFINER, so revoke the implicit PUBLIC grant.
-- ---------------------------------------------------------------------------

revoke all on function public.require_profile() from public;
revoke all on function public.require_staff() from public;
revoke all on function public.request_dismissal(uuid[], text, text) from public;
revoke all on function public.staff_add_to_queue(uuid, text) from public;
revoke all on function public.set_request_status(uuid, public.dismissal_status) from public;
revoke all on function public.call_next_student() from public;
revoke all on function public.cancel_request(uuid, text) from public;
revoke all on function public.end_dismissal_session() from public;

grant execute on function public.request_dismissal(uuid[], text, text) to authenticated;
grant execute on function public.staff_add_to_queue(uuid, text) to authenticated;
grant execute on function public.set_request_status(uuid, public.dismissal_status) to authenticated;
grant execute on function public.call_next_student() to authenticated;
grant execute on function public.cancel_request(uuid, text) to authenticated;
grant execute on function public.end_dismissal_session() to authenticated;

-- ---------------------------------------------------------------------------
-- Realtime — stream queue changes to every connected device.
-- REPLICA IDENTITY FULL lets Realtime apply RLS to UPDATE/DELETE payloads.
-- ---------------------------------------------------------------------------

alter table public.dismissal_requests replica identity full;

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime'
      and schemaname = 'public'
      and tablename = 'dismissal_requests'
  ) then
    alter publication supabase_realtime add table public.dismissal_requests;
  end if;
exception
  when undefined_object then
    -- No `supabase_realtime` publication (plain Postgres); nothing to do.
    null;
end;
$$;

-- ###########################################################################
-- 20260101000003_classes.sql
-- ###########################################################################

-- ===========================================================================
-- AGS Dismissal — class structure and parent-initiated calls
-- ---------------------------------------------------------------------------
-- AGS names classes by grade, gender and section: "7g1" is grade 7, girls,
-- section 1; "8b2" is grade 8, boys, section 2. Kindergarten (KG1–KG3) is
-- mixed and lettered: "KG2-A". Every class gets its own board.
--
-- Dismissal is driven by parents: their "I'm here" IS the call, so a request
-- is created already in the `called` state and the name turns yellow on the
-- class board. The teacher then marks the student dismissed (`picked_up`).
-- ===========================================================================

create type public.class_gender as enum ('boys', 'girls', 'mixed');

alter table public.classrooms
  add column level   text not null default '',
  add column gender  public.class_gender not null default 'mixed',
  add column section text not null default '';

comment on column public.classrooms.name    is 'Class code teachers use: 7g1, 8b2, KG2-A.';
comment on column public.classrooms.level   is 'KG1–KG3 or 1–12.';
comment on column public.classrooms.section is '1–6 for grades, A–F for kindergarten.';

-- ---------------------------------------------------------------------------
-- Parent / driver: "I'm here" creates the call itself.
-- ---------------------------------------------------------------------------

create or replace function public.request_dismissal(
  p_student_ids uuid[],
  p_note text default null,
  p_vehicle text default null
)
returns setof public.dismissal_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile  public.profiles := public.require_profile();
  v_student  uuid;
  v_existing public.dismissal_requests;
  v_new      public.dismissal_requests;
begin
  if p_student_ids is null or array_length(p_student_ids, 1) is null then
    raise exception 'Choose at least one student.' using errcode = '22023';
  end if;

  foreach v_student in array p_student_ids loop
    if not public.is_guardian_of(v_student) then
      raise exception 'You are not authorised to pick up this student.'
        using errcode = '42501';
    end if;

    select * into v_existing
      from public.dismissal_requests
     where student_id = v_student
       and status in ('requested', 'waiting', 'called', 'ready')
     limit 1;

    if v_existing.id is not null then
      return next v_existing;
      continue;
    end if;

    insert into public.dismissal_requests (
      student_id, status, source, requested_by, called_at, note, vehicle_description
    )
    values (
      v_student,
      'called',
      'parent_app',
      v_profile.id,
      now(),
      nullif(trim(coalesce(p_note, '')), ''),
      coalesce(nullif(trim(coalesce(p_vehicle, '')), ''), v_profile.vehicle_description)
    )
    returning * into v_new;

    return next v_new;
  end loop;
end;
$$;

-- ---------------------------------------------------------------------------
-- Staff fallback: a guardian arrived without the app.
-- ---------------------------------------------------------------------------

create or replace function public.staff_call_student(p_student_id uuid)
returns public.dismissal_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile  public.profiles := public.require_staff();
  v_school   uuid;
  v_existing public.dismissal_requests;
  v_new      public.dismissal_requests;
begin
  select school_id into v_school from public.students where id = p_student_id and is_active;

  if v_school is null or v_school <> v_profile.school_id then
    raise exception 'That student is not enrolled at your school.' using errcode = '42501';
  end if;

  select * into v_existing
    from public.dismissal_requests
   where student_id = p_student_id
     and status in ('requested', 'waiting', 'called', 'ready')
   limit 1;

  if v_existing.id is not null then
    return public.set_request_status(v_existing.id, 'called');
  end if;

  insert into public.dismissal_requests (student_id, status, source, requested_by, called_by, called_at)
  values (p_student_id, 'called', 'staff', v_profile.id, v_profile.id, now())
  returning * into v_new;

  return v_new;
end;
$$;

revoke all on function public.staff_call_student(uuid) from public;
grant execute on function public.staff_call_student(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Parents may cancel their own call until the teacher has dismissed the child.
-- ---------------------------------------------------------------------------

create or replace function public.cancel_request(
  p_request_id uuid,
  p_reason text default null
)
returns public.dismissal_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile       public.profiles := public.require_profile();
  v_request       public.dismissal_requests;
  v_parent_cancel boolean;
begin
  select * into v_request from public.dismissal_requests where id = p_request_id;

  if v_request.id is null then
    raise exception 'That dismissal request could not be found.' using errcode = 'P0002';
  end if;

  if v_request.status in ('picked_up', 'cancelled') then
    raise exception 'That dismissal is already closed.' using errcode = '22023';
  end if;

  if v_profile.role in ('admin', 'staff') then
    if v_request.school_id <> v_profile.school_id then
      raise exception 'That dismissal request belongs to another school.' using errcode = '42501';
    end if;
  else
    if not public.is_guardian_of(v_request.student_id) then
      raise exception 'You are not authorised to change this dismissal.' using errcode = '42501';
    end if;

    select allow_parent_cancel into v_parent_cancel
      from public.schools where id = v_request.school_id;

    if not coalesce(v_parent_cancel, false) then
      raise exception 'Your school asks that you contact the office to cancel a pickup.'
        using errcode = '42501';
    end if;
  end if;

  update public.dismissal_requests
     set status        = 'cancelled',
         cancelled_at  = now(),
         cancel_reason = nullif(trim(coalesce(p_reason, '')), '')
   where id = p_request_id
   returning * into v_request;

  return v_request;
end;
$$;

-- ---------------------------------------------------------------------------
-- Status changes keep the original call intact: who called and when is set
-- once (by the parent, or by staff on a manual call) and never rewritten by
-- a dismissal or an undo.
-- ---------------------------------------------------------------------------

create or replace function public.set_request_status(
  p_request_id uuid,
  p_status public.dismissal_status
)
returns public.dismissal_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile public.profiles := public.require_staff();
  v_request public.dismissal_requests;
  v_now     timestamptz := now();
begin
  select * into v_request from public.dismissal_requests where id = p_request_id;

  if v_request.id is null or v_request.school_id <> v_profile.school_id then
    raise exception 'That dismissal request could not be found.' using errcode = 'P0002';
  end if;

  if p_status = 'cancelled' then
    raise exception 'Use cancel_request() to cancel a dismissal.' using errcode = '22023';
  end if;

  if p_status = 'requested' then
    raise exception 'Only a parent or driver can create an arrival request.'
      using errcode = '22023';
  end if;

  update public.dismissal_requests
     set status       = p_status,
         called_at    = case when p_status = 'waiting' then null else coalesce(called_at, v_now) end,
         called_by    = case
                          when p_status = 'waiting' then null
                          -- A staff-originated call is attributed to whoever completes it;
                          -- a parent's call keeps the parent as the caller.
                          when source = 'staff' then coalesce(called_by, v_profile.id)
                          else called_by
                        end,
         ready_at     = case
                          when p_status in ('waiting', 'called') then null
                          when p_status = 'ready' then v_now
                          else coalesce(ready_at, v_now)
                        end,
         picked_up_at = case when p_status = 'picked_up' then v_now else null end,
         released_by  = case when p_status = 'picked_up' then v_profile.id else null end,
         cancelled_at = null,
         cancel_reason = null
   where id = p_request_id
   returning * into v_request;

  return v_request;
exception
  when unique_violation then
    raise exception 'That student already has another active dismissal in the queue.'
      using errcode = '23505';
end;
$$;

-- ---------------------------------------------------------------------------
-- A classroom screen (display role) renders a class board, which needs the
-- names on the roster — not just the calls.
-- ---------------------------------------------------------------------------

drop policy if exists "staff read students in their school" on public.students;
create policy "school staff and screens read students"
  on public.students for select to authenticated
  using (school_id = public.current_school_id() and public.is_board_viewer());

-- ###########################################################################
-- 20260101000004_roles.sql
-- ###########################################################################

-- ===========================================================================
-- AGS Dismissal — simplify the role model
-- ---------------------------------------------------------------------------
-- Two roles turned out not to exist at AGS:
--
--   • `display` — there is no separate read-only classroom screen. A teacher
--     signs in and can see and do everything on their class boards.
--   • a distinct "driver" — a driver is simply a parent-role account linked to
--     a student. Which relationship they have (Mother, Father, Driver) is the
--     `guardians.relationship` field, not a role.
--
-- Roles are now: admin, staff, parent.
-- ===========================================================================

-- 1. Nobody is a display account any more.
update public.profiles set role = 'staff' where role = 'display';

-- 2. Redefine the helper before the value disappears from the enum, so the
--    function body no longer names it. Board access is simply staff access.
create or replace function public.is_board_viewer()
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.profiles
    where id = auth.uid() and is_active and role in ('admin', 'staff')
  );
$$;

comment on function public.is_board_viewer() is
  'Kept as the name the RLS policies use; now identical to is_staff().';

-- 3. Swap the enum. `current_role_name()` returns the old type, and a return
--    type cannot be changed in place, so it is dropped and rebuilt.
drop function if exists public.current_role_name();

alter type public.user_role rename to user_role_legacy;
create type public.user_role as enum ('admin', 'staff', 'parent');

alter table public.profiles
  alter column role drop default,
  alter column role type public.user_role using role::text::public.user_role,
  alter column role set default 'parent';

-- Rebuilt against the new type.
create function public.current_role_name()
returns public.user_role
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select role from public.profiles where id = auth.uid() and is_active;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, school_id, role, full_name, email, phone)
  values (
    new.id,
    nullif(new.raw_user_meta_data ->> 'school_id', '')::uuid,
    coalesce(nullif(new.raw_user_meta_data ->> 'role', ''), 'parent')::public.user_role,
    coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), split_part(new.email, '@', 1)),
    new.email,
    nullif(new.raw_user_meta_data ->> 'phone', '')
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = case
          when public.profiles.full_name = '' then excluded.full_name
          else public.profiles.full_name
        end;
  return new;
end;
$$;

drop type public.user_role_legacy;

-- 4. The students policy is about staff, not screens.
drop policy if exists "school staff and screens read students" on public.students;
create policy "staff read students in their school"
  on public.students for select to authenticated
  using (school_id = public.current_school_id() and public.is_staff());

grant execute on function public.current_role_name() to authenticated;
grant execute on function public.is_board_viewer() to authenticated;

-- ###########################################################################
-- 20260101000005_scopes_and_promotion.sql
-- ###########################################################################

-- ===========================================================================
-- AGS Dismissal — shared section accounts, student gender, year promotion
-- ---------------------------------------------------------------------------
-- AGS signs in with ONE shared account per section rather than per teacher:
--
--   dismissal.boys@ags.edu.sa   → every boys' class
--   dismissal.girls@ags.edu.sa  → every girls' class
--   dismissal.kg@ags.edu.sa     → the mixed kindergarten classes
--
-- `profiles.section_scope` is what makes that safe: the boys account cannot
-- read a girls' class, its roster, or its calls — enforced by RLS, not by the
-- screen. Administrators get scope 'all'.
-- ===========================================================================

create type public.section_scope as enum ('boys', 'girls', 'mixed', 'all');

alter table public.profiles
  add column section_scope public.section_scope not null default 'all';

comment on column public.profiles.section_scope is
  'Which classes this account may open. ''all'' is unrestricted (administrators).';

-- Kindergarten is mixed, so a KG student''s own gender is the only thing that
-- can decide which Grade 1 class they move into at promotion.
alter table public.students
  add column gender public.class_gender;

comment on column public.students.gender is
  'boys/girls. Required to promote a mixed KG class into split Grade 1 classes.';

-- Backfill from the class the student is already in.
update public.students s
   set gender = c.gender
  from public.classrooms c
 where s.classroom_id = c.id and c.gender <> 'mixed';

-- Snapshot the section onto each call so the board filter and the RLS check
-- are a single-column test rather than a join.
alter table public.dismissal_requests
  add column class_gender public.class_gender;

create index dismissal_requests_section_idx
  on public.dismissal_requests (school_id, dismissal_date, class_gender);

-- ---------------------------------------------------------------------------
-- Scope helpers
-- ---------------------------------------------------------------------------

create or replace function public.current_scope()
returns public.section_scope
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select section_scope from public.profiles where id = auth.uid() and is_active;
$$;

/** True when the caller's account may open a class of this section. */
create or replace function public.scope_allows(p_gender public.class_gender)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select case
    when public.current_scope() = 'all' then true
    when p_gender is null then false
    else public.current_scope()::text = p_gender::text
  end;
$$;

create or replace function public.student_gender(p_student_id uuid)
returns public.class_gender
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select coalesce(s.gender, c.gender)
    from public.students s
    left join public.classrooms c on c.id = s.classroom_id
   where s.id = p_student_id;
$$;

grant execute on function public.current_scope() to authenticated;
grant execute on function public.scope_allows(public.class_gender) to authenticated;
grant execute on function public.student_gender(uuid) to authenticated;

-- ---------------------------------------------------------------------------
-- Snapshot the section when a call is created
-- ---------------------------------------------------------------------------

create or replace function public.tg_snapshot_request()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_student record;
  v_tz      text;
begin
  select s.school_id,
         trim(s.first_name || ' ' || s.last_name) as full_name,
         s.grade,
         s.pickup_number,
         c.name as classroom_name,
         coalesce(c.gender, s.gender) as class_gender
    into v_student
    from public.students s
    left join public.classrooms c on c.id = s.classroom_id
   where s.id = new.student_id;

  if v_student is null then
    raise exception 'Student % does not exist', new.student_id
      using errcode = 'foreign_key_violation';
  end if;

  new.school_id      := v_student.school_id;
  new.student_name   := v_student.full_name;
  new.student_grade  := v_student.grade;
  new.classroom_name := v_student.classroom_name;
  new.class_gender   := v_student.class_gender;
  new.pickup_number  := coalesce(nullif(new.pickup_number, ''), v_student.pickup_number);

  select timezone into v_tz from public.schools where id = new.school_id;
  new.dismissal_date := (now() at time zone coalesce(v_tz, 'UTC'))::date;

  if new.requested_by is not null then
    select full_name into new.guardian_name from public.profiles where id = new.requested_by;
  end if;

  return new;
end;
$$;

-- ---------------------------------------------------------------------------
-- Re-scope the staff read policies
-- ---------------------------------------------------------------------------

drop policy if exists "staff read students in their school" on public.students;
create policy "staff read students in their section"
  on public.students for select to authenticated
  using (
    school_id = public.current_school_id()
    and public.is_staff()
    and public.scope_allows(public.student_gender(students.id))
  );

drop policy if exists "staff read classrooms" on public.classrooms;
create policy "staff read classrooms in their section"
  on public.classrooms for select to authenticated
  using (
    school_id = public.current_school_id()
    and public.is_board_viewer()
    and public.scope_allows(classrooms.gender)
  );

drop policy if exists "staff and boards read the queue" on public.dismissal_requests;
create policy "staff read calls in their section"
  on public.dismissal_requests for select to authenticated
  using (
    school_id = public.current_school_id()
    and public.is_board_viewer()
    and public.scope_allows(dismissal_requests.class_gender)
  );

-- Staff may only act on a class inside their own section.
create or replace function public.require_staff_for_student(p_student_id uuid)
returns public.profiles
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile public.profiles := public.require_staff();
  v_school  uuid;
begin
  select school_id into v_school from public.students where id = p_student_id;

  if v_school is null or v_school <> v_profile.school_id then
    raise exception 'That student is not enrolled at your school.' using errcode = '42501';
  end if;

  if not public.scope_allows(public.student_gender(p_student_id)) then
    raise exception 'That class is not in your section.' using errcode = '42501';
  end if;

  return v_profile;
end;
$$;

revoke all on function public.require_staff_for_student(uuid) from public;

-- ---------------------------------------------------------------------------
-- Section-aware call + dismiss
-- ---------------------------------------------------------------------------

create or replace function public.staff_call_student(p_student_id uuid)
returns public.dismissal_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile  public.profiles := public.require_staff_for_student(p_student_id);
  v_existing public.dismissal_requests;
  v_new      public.dismissal_requests;
begin
  select * into v_existing
    from public.dismissal_requests
   where student_id = p_student_id
     and status in ('requested', 'waiting', 'called', 'ready')
   limit 1;

  if v_existing.id is not null then
    return public.set_request_status(v_existing.id, 'called');
  end if;

  insert into public.dismissal_requests (student_id, status, source, requested_by, called_by, called_at)
  values (p_student_id, 'called', 'staff', v_profile.id, v_profile.id, now())
  returning * into v_new;

  return v_new;
end;
$$;

create or replace function public.set_request_status(
  p_request_id uuid,
  p_status public.dismissal_status
)
returns public.dismissal_requests
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_request public.dismissal_requests;
  v_profile public.profiles;
  v_now     timestamptz := now();
begin
  select * into v_request from public.dismissal_requests where id = p_request_id;

  if v_request.id is null then
    raise exception 'That dismissal request could not be found.' using errcode = 'P0002';
  end if;

  -- Also proves the caller's section covers this student's class.
  v_profile := public.require_staff_for_student(v_request.student_id);

  if p_status = 'cancelled' then
    raise exception 'Use cancel_request() to cancel a dismissal.' using errcode = '22023';
  end if;

  if p_status = 'requested' then
    raise exception 'Only a parent or driver can create an arrival request.'
      using errcode = '22023';
  end if;

  update public.dismissal_requests
     set status       = p_status,
         called_at    = case when p_status = 'waiting' then null else coalesce(called_at, v_now) end,
         called_by    = case
                          when p_status = 'waiting' then null
                          when source = 'staff' then coalesce(called_by, v_profile.id)
                          else called_by
                        end,
         ready_at     = case
                          when p_status in ('waiting', 'called') then null
                          when p_status = 'ready' then v_now
                          else coalesce(ready_at, v_now)
                        end,
         picked_up_at = case when p_status = 'picked_up' then v_now else null end,
         released_by  = case when p_status = 'picked_up' then v_profile.id else null end,
         cancelled_at = null,
         cancel_reason = null
   where id = p_request_id
   returning * into v_request;

  return v_request;
exception
  when unique_violation then
    raise exception 'That student already has another active dismissal in the queue.'
      using errcode = '23505';
end;
$$;

-- ---------------------------------------------------------------------------
-- End-of-year promotion
-- ---------------------------------------------------------------------------

/** KG1 → KG2 → KG3 → 1 → 2 … → 12. Grade 12 has nowhere to go. */
create or replace function public.next_level(p_level text)
returns text
language sql
immutable
as $$
  select case
    when p_level = 'KG1' then 'KG2'
    when p_level = 'KG2' then 'KG3'
    when p_level = 'KG3' then '1'
    when p_level ~ '^[0-9]+$' and p_level::int < 12 then (p_level::int + 1)::text
    else null
  end;
$$;

/** Sections are lettered in kindergarten and numbered in the grades. */
drop function if exists public.next_section(text, boolean);
create function public.next_section(p_section text, p_to_kg boolean)
returns text
language sql
immutable
as $$
  -- Sections are lettered in kindergarten and numbered in the grades, so what
  -- decides the notation is where the student is GOING, not where they came
  -- from. KG1-A becomes KG2-A; KG3-B becomes Grade 1 section 2.
  select case
    when p_to_kg then
      case
        when upper(p_section) between 'A' and 'F' then upper(p_section)
        when p_section ~ '^[1-6]$' then chr(ascii('A') + p_section::int - 1)
        else 'A'
      end
    else
      case
        when p_section ~ '^[1-9][0-9]*$' then p_section
        when upper(p_section) between 'A' and 'F'
          then (ascii(upper(p_section)) - ascii('A') + 1)::text
        else '1'
      end
  end;
$$;

/**
 * Moves every student up one grade, at the end of the school year.
 *
 * Grade 12 leaves the school: those students are deleted along with their
 * dismissal history, which is what AGS asked for. Everything else moves into
 * the same section one level up, and the target class is created if it does
 * not exist yet.
 *
 * A kindergarten student with no recorded gender cannot be placed into a split
 * Grade 1 class; those are left where they are and reported back so the office
 * can fix them.
 */
create or replace function public.promote_all_students()
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_profile   public.profiles := public.require_profile();
  v_graduated integer := 0;
  v_promoted  integer := 0;
  v_skipped   integer := 0;
  v_row       record;
  v_level     text;
  v_gender    public.class_gender;
  v_section   text;
  v_target    uuid;
begin
  if v_profile.role <> 'admin' then
    raise exception 'Only a school administrator can promote the whole school.'
      using errcode = '42501';
  end if;

  -- 1. Grade 12 leaves.
  delete from public.students s
   using public.classrooms c
   where s.classroom_id = c.id
     and s.school_id = v_profile.school_id
     and c.level = '12';
  get diagnostics v_graduated = row_count;

  -- 2. Everyone else moves up. Highest grades first so a class never receives
  --    students before its own occupants have left it.
  for v_row in
    select s.id as student_id, s.gender as student_gender,
           c.level, c.gender as class_gender, c.section
      from public.students s
      join public.classrooms c on c.id = s.classroom_id
     where s.school_id = v_profile.school_id
     order by case when c.level ~ '^[0-9]+$' then c.level::int else -1 end desc
  loop
    v_level := public.next_level(v_row.level);
    if v_level is null then
      continue;
    end if;

    -- Leaving kindergarten means the student's own gender decides the class.
    if v_level = '1' then
      v_gender := v_row.student_gender;
      if v_gender is null or v_gender = 'mixed' then
        v_skipped := v_skipped + 1;
        continue;
      end if;
    else
      v_gender := v_row.class_gender;
    end if;

    v_section := public.next_section(v_row.section, v_level like 'KG%');

    select id into v_target
      from public.classrooms
     where school_id = v_profile.school_id
       and level = v_level
       and gender = v_gender
       and section = v_section;

    if v_target is null then
      insert into public.classrooms (school_id, name, grade, level, gender, section)
      values (
        v_profile.school_id,
        case when v_level like 'KG%'
             then v_level || '-' || v_section
             else v_level || case when v_gender = 'girls' then 'g' else 'b' end || v_section
        end,
        case when v_level like 'KG%' then 'KG ' || right(v_level, 1) else 'Grade ' || v_level end,
        v_level,
        v_gender,
        v_section
      )
      returning id into v_target;
    end if;

    update public.students
       set classroom_id = v_target,
           gender = coalesce(gender, v_gender),
           grade = (select grade from public.classrooms where id = v_target)
     where id = v_row.student_id;

    v_promoted := v_promoted + 1;
  end loop;

  return jsonb_build_object(
    'promoted', v_promoted,
    'graduated', v_graduated,
    'skipped', v_skipped
  );
end;
$$;

revoke all on function public.promote_all_students() from public;
grant execute on function public.promote_all_students() to authenticated;

-- ---------------------------------------------------------------------------
-- New accounts carry their section from sign-up metadata.
--
-- The Edge Function that creates staff logins passes `section_scope` in the
-- user metadata; without this the trigger would drop it and every new teacher
-- account would silently see the whole school.
-- ---------------------------------------------------------------------------

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public, pg_temp
as $$
begin
  insert into public.profiles (id, school_id, role, full_name, email, phone, section_scope)
  values (
    new.id,
    nullif(new.raw_user_meta_data ->> 'school_id', '')::uuid,
    coalesce(nullif(new.raw_user_meta_data ->> 'role', ''), 'parent')::public.user_role,
    coalesce(nullif(new.raw_user_meta_data ->> 'full_name', ''), split_part(new.email, '@', 1)),
    new.email,
    nullif(new.raw_user_meta_data ->> 'phone', ''),
    coalesce(nullif(new.raw_user_meta_data ->> 'section_scope', ''), 'all')::public.section_scope
  )
  on conflict (id) do update
    set email = excluded.email,
        full_name = case
          when public.profiles.full_name = '' then excluded.full_name
          else public.profiles.full_name
        end;
  return new;
end;
$$;

-- ###########################################################################
-- Proof the paste arrived in one piece.
--
-- The SQL editor shows the result of the last statement. If you do not see a
-- row saying "installed", the paste was cut short — copy the file again and
-- re-run it; the guard at the top will clear the partial install for you.
-- ###########################################################################

select
  'installed' as ags_dismissal,
  (select count(*) from pg_tables where schemaname = 'public') as tables,
  (select count(*) from pg_policies where schemaname = 'public') as policies,
  'Now run supabase/setup.sql' as next_step;
